logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org4
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8888